# Generated by Django 4.0.3 on 2022-04-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_referencias_delete_teste_jobs_referencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='C', max_length=2),
        ),
    ]
